### PR TITLE
Fix compilation on macOS 10.14.6/Xcode 10.2.1

### LINKED ISSUE #1: Fails to build on macOS 10.14.6/Xcode 10.2.1
```
$ make -j4
[ 11%] Building CXX object CMakeFiles/jiyu.dir/src/os_support.cpp.o
jiyu/src/os_support.cpp:47:19: error: use of undeclared identifier '_NSGetExecutablePath'
    auto result = _NSGetExecutablePath(buf, &bufsize);
                  ^
jiyu/src/os_support.cpp:48:29: error: no viable conversion from returned value of type
      'const char [1]' to function return type 'String'
    if (result != 0) return "";
                            ^~
jiyu/src/general.h:29:8: note: candidate constructor (the implicit copy constructor) not viable:
      no known conversion from 'const char [1]' to 'const String &' for 1st argument
struct String {
       ^
jiyu/src/general.h:29:8: note: candidate constructor (the implicit move constructor) not viable:
      no known conversion from 'const char [1]' to 'String &&' for 1st argument
jiyu/src/os_support.cpp:61:30: error: use of undeclared identifier 'F_OK'
        bool result = access(c_str, F_OK) != -1;
                                    ^
3 errors generated.
make[2]: *** [CMakeFiles/jiyu.dir/src/os_support.cpp.o] Error 1
make[1]: *** [CMakeFiles/jiyu.dir/all] Error 2
make: *** [all] Error 2
```
```
$ clang --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Also, I'm using the binary `clang+llvm-8.0.0-x86_64-apple-darwin` downloaded from LLVM's official website instead of building from source; I don't think that would cause these errors though.

### PR DESCRIPTION
**Pull request by zhuowei**
This fixes #1.

----

Note: I've only tested this on my own computer; I'm not sure if other Macs need these changes, or maybe my computer's just screwed up.

### CODE REVIEW

**Comment by machinamentum** [comment]
Admittedly, I did not test the change that broke this on macOS prior to checking in. Thanks!
